name: "build_wasm"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.x"

      - name: Install rollup
        run: |
          npm install --global rollup@4.28.1

      - name: Build all WASM and generate npm package
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/build-all.sh

      - name: Publish to npm
        run: |
          cd aptos-confidential-asset-wasm-bindings
          ls -R .
          cat package.json
          npm pkg fix
          npm pack
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_ACCESS_TOKEN }}
          npm publish --access public
